#+TITLE: Standard Operating Procedure
#+AUTHOR: David James, davidabraham@ucla.edu
#+DATE: 2020 April 04

* Installation
  This SOP assumes that you have python already installed. Before you get to run
  the program you'll need to ensure that you have all the dependencies that the
  programs run on. Because of how most of this program is setup, you will do most of the interaction with code through the terminal.
  1. If you are on Windows, open the ~Powershell~. If you are on Mac, open the ~Terminal~.
  2. Next you will need to move over to the the directory that contains the files that you unzipped.
  3. First make sure your package manager is up-to-date.
     #+BEGIN_SRC bash
       # if you are on a Windows machine, run this command
       python -m pip install --upgrade pip

       # if you are on a Mac, run this command
       pip install --upgrade pip
     #+END_SRC
  4. Next you'll be installing the dependencies.
     #+BEGIN_SRC bash
       pip install -r requirements.txt
     #+END_SRC
* Synthetic Movie Program
  At this point, you should have Python and all the dependencies to run the
  programs. This first one creates a synthetic .avi movie for use with DigiPyRo.
  The video shows a ball rolling on a parabolic surface, where the user may
  change the video length of the movie, frame rate, resolution, frequncy of
  oscillations, rotation rate of the reference frame, and control the inital
  conditions of the ball.
  1. You will still need the terminal at this point, so open it up if you have closed it.
  2.
* DigiPyRo Program
