#+TITLE: README
#+AUTHOR: David James, davidabraham@ucla.edu
#+DATE: 2020 June 19


* Synthesizer
  1. Present
     - project runs as a CLI
     - shows the inertial path along with the absolute path
     - NOTE :: The animation has a switch to run it live or just save it. Running it live is mainly for quick debugging. It is not perfect, and the watermarks on it come out larger, but get fixed to their correct size when the film is saved. If the live feature wants to be used in the future for the project, it will need to be sped up and the image sizing will need to be fixed.
  2. Future
     - a dot at the center of the paraboloid should be placed so DPR is easier to use with it
     - have an on/off for a grid on synth
     - have an on/off for the inertial path to be shown
     - show time/omega as animation progresses
     - have different grid options (i.e. concentric circles or square grid)
     - have a message show that puck has gone off the paraboloid
     - The watermarks have been added, but the DIYnamics logo is difficult to read. A new one that can fit with the black background should perhaps be designed.

* DigiPyRo
  1. Present
     - project runs as a CLI
     - rotates a film dependent on the RPM given
  2. Future
     - Fix elliptical warping that happens on some films being scaled
     - Have so side-by-side of rotated and de-rotated films
     - Enable particle tracking
     - have a timestamp shown on the film
     - NOTE :: =digipyro.old.py= is Sam May's implementation. Many of the features planned for the is already designed into his code, but needs to be moved over, so that it fits with the modular design that this code is now following.

* Future
  Overall, synth and digipyro is cleaned up a lot, and are being designed with a modular mindset, so code can be found and "easily" updated. The other main module will be a GUI that will implement these synth and digipyro functions, and app.py will run it all seamlessly.
